version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: true

hooks:
  AfterInstall:
    - location: deploy/scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deploy/scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: deploy/scripts/validate.sh
      timeout: 300
      runas: root
